import RoomListItem from "./RoomListItem";

export default function RoomList() {
  return (
    <div>
      <ul className=" max-h-[50vh]  overflow-y-auto ml-8 p-2">
        <RoomListItem
          name="asasdjnsdjsasldnsldn"
          category="Anime"
          currentNumberOfPlayers={2}
          maximumNumberOfPlayers={1}
        />
        <RoomListItem
          name="asd"
          category="Anime"
          currentNumberOfPlayers={2}
          maximumNumberOfPlayers={1}
        />
        <RoomListItem
          name="asd"
          category="Anime"
          currentNumberOfPlayers={2}
          maximumNumberOfPlayers={1}
        />
        <RoomListItem
          name="asd"
          category="Anime"
          currentNumberOfPlayers={2}
          maximumNumberOfPlayers={1}
        />
        <RoomListItem
          name="asd"
          category="Anime"
          currentNumberOfPlayers={2}
          maximumNumberOfPlayers={1}
        />
        <RoomListItem
          name="asd"
          category="Anime"
          currentNumberOfPlayers={2}
          maximumNumberOfPlayers={1}
        />
        <RoomListItem
          name="asd"
          category="Anime"
          currentNumberOfPlayers={2}
          maximumNumberOfPlayers={1}
        />
        <RoomListItem
          name="asd"
          category="Anime"
          currentNumberOfPlayers={2}
          maximumNumberOfPlayers={1}
        />
        <RoomListItem
          name="asd"
          category="Anime"
          currentNumberOfPlayers={2}
          maximumNumberOfPlayers={1}
        />
        <RoomListItem
          name="asd"
          category="Anime"
          currentNumberOfPlayers={2}
          maximumNumberOfPlayers={1}
        />
        <RoomListItem
          name="asd"
          category="Anime"
          currentNumberOfPlayers={2}
          maximumNumberOfPlayers={1}
        />
        <RoomListItem
          name="asd"
          category="Anime"
          currentNumberOfPlayers={2}
          maximumNumberOfPlayers={1}
        />
        <RoomListItem
          name="asd"
          category="Anime"
          currentNumberOfPlayers={2}
          maximumNumberOfPlayers={1}
        />
        <RoomListItem
          name="asd"
          category="Anime"
          currentNumberOfPlayers={2}
          maximumNumberOfPlayers={1}
        />
      </ul>
    </div>
  );
}
